[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
cbor_metadata = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[invariant]
runs = 1000           # Number of times to run the invariant test campaign
depth = 100           # Number of calls per invariant test campaign
fail_on_revert = true # Whether or not to fail the test if a call reverts

[rpc_endpoints]
bnb = "${BSC_RPC_URL}"
base = "${BASE_RPC_URL}"
sonic = "${SONIC_RPC_URL}"

[etherscan]
sonic = { key = "${SONICSCAN_API_KEY}", url = "https://api.sonicscan.org/api" }
bnb = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.sonicscan.org/api" }
